src/Entity/Parcel.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiFilter;
use ApiPlatform\Core\Annotation\ApiResource;
use Symfony\Component\Serializer\Annotation\Groups;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\SearchFilter;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ApiFilter(SearchFilter::class, properties={"yearPlan": "exact"})
 * @ApiResource( 
 * itemOperations={"get"={"security"="is_granted('ROLE_ADMIN')"}},
 * collectionOperations={"get"={"security"="is_granted('ROLE_USER')"}},
 * normalizationContext={"groups"={"parcel:read"}} 
 * )
 * @ORM\Entity(repositoryClass="App\Repository\ParcelRepository")
 */
class Parcel
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @Groups({"parcel:read"})
     */
    private $id;

    /**
     * @Groups({"parcel:read"})
     * @ORM\Column(type="string", length=10)
     */
    private $parcelNumber;

    /**
     * @Groups({"parcel:read"})
     * @ORM\Column(type="integer")
     */
    private $cultivatedArea;

    /**
     * @Groups({"parcel:read"})
     * @ORM\Column(type="boolean")
     */
    private $fuelApplication;

    /**
     * @Groups({"parcel:read"})
     * @ORM\ManyToOne(targetEntity="App\Entity\Operator", inversedBy="parcels")
     */
    private $ArimrOperator;

    /**
     * @Groups({"parcel:read"})
     * @ORM\ManyToOne(targetEntity="App\Entity\YearPlan", inversedBy="parcels")
     * @ORM\JoinColumn(nullable=false)
     */
    private $yearPlan;

    /**
     * @Groups({"parcel:read"})
     * @ORM\ManyToOne(targetEntity="App\Entity\Field", inversedBy="parcels")
     */
    private $field;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getParcelNumber(): ?string
    {
        return $this->parcelNumber;
    }

    public function setParcelNumber(string $parcelNumber): self
    {
        $this->parcelNumber = $parcelNumber;

        return $this;
    }

    public function getCultivatedArea(): ?int
    {
        return $this->cultivatedArea;
    }
    public function getCultivatedAreaHa(): ?float
    {
        return round(($this->cultivatedArea/100),2);
    }

    public function setCultivatedArea(int $cultivatedArea): self
    {
        $this->cultivatedArea = $cultivatedArea;

        return $this;
    }

    public function getFuelApplication(): ?bool
    {
        return $this->fuelApplication;
    }

    public function setFuelApplication(bool $fuelApplication): self
    {
        $this->fuelApplication = $fuelApplication;

        return $this;
    }

    public function getArimrOperator(): ?Operator
    {
        return $this->ArimrOperator;
    }

    public function setArimrOperator(?Operator $ArimrOperator): self
    {
        $this->ArimrOperator = $ArimrOperator;

        return $this;
    }

    public function getYearPlan(): ?yearPlan
    {
        return $this->yearPlan;
    }

    public function setYearPlan(?yearPlan $yearPlan): self
    {
        $this->yearPlan = $yearPlan;

        return $this;
    }

    public function getField(): ?field
    {
        return $this->field;
    }

    public function setField(?field $field): self
    {
        $this->field = $field;

        return $this;
    }
}

src/Controller/DataController.php
<?php

namespace App\Controller;

use App\Entity\Field;
use App\Entity\Parcel;
use App\Entity\UserPlant;
use App\Entity\YearPlan;
use App\Entity\Plant;
use App\Form\NewFieldFormType;
use App\Form\NewYearPlanFormType;
use App\Form\UserPlantsType;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Validator\ValidatorInterface;

class DataController extends AbstractController {

    /**
     * @Route("yearPlan", name="chooseYearPlan")
     */
    public function chooseYearPlan() {
        $user = $this->getUser();
        $userYearPlans = $user->getYearPlans();
        return $this->render('data/chooseYearPlan.twig', ['yearPlanCollection' => $userYearPlans]);
    }

    /**
     * @Route("setYearPlan", name="setYearPlan")
     */
    public function setYearPlan(Request $request) {
        $user = $this->getUser();

// From POST
        $yearPlanId = $request->request->get('yearPlan');

        $yearPlan = DataController::findYearPlanById($yearPlanId);
        if ($yearPlan) {
            $user->setChoosedYearPlan($yearPlan);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->flush();
        }
        return $this->redirectToRoute('main');
    }

    /**
     * @Route("yearPlan/status", name="yearPlanStatus")
     */
    public function yearPlanChangeStatus(Request $request) {
        $user = $this->getUser();
        $userYearPlans = $user->getYearPlans();

// From POST
        $yearPlanId = $request->request->get('yearPlan');
        $status = $request->request->get('status');

        $yearPlan = DataController::findEntityById($userYearPlans, $yearPlanId);

        if ($yearPlan) {
// Change status
            $status == "open" ? $yearPlan->setIsClosed(true) : $yearPlan->setIsClosed(false);
// Save to database
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->flush();
        }
        return $this->redirectToRoute('yearPlanList');
    }

    /**
     * @Route("yearPlan/add", name="addYearPlan")
     */
    public function addYearPlan(ValidatorInterface $validator, Request $request) {
        $user = $this->getUser();
        $yearPlan = new YearPlan();
        $yearPlan->setUser($user);

        $form = $this->createForm(NewYearPlanFormType::class, $yearPlan, ['yearPlans' => $user->getYearPlans()]);
        $form->handleRequest($request);

        $errors = $validator->validate($yearPlan);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $yearPlanToImport = $form->get('import')->getData();
            $yearPlan->setEndYear($yearPlan->getStartYear() + 1);
            $entityManager->persist($yearPlan);

            if ($yearPlanToImport) { //Import settings from other YearPlan
                DataController::deepSave($yearPlanToImport, $yearPlan);
            }
            $entityManager->flush();
            return $this->redirectToRoute('chooseYearPlan');
        }

        $parameters = [
            'newYearPlanForm' => $form->createView(),
            'errors' => $errors
        ];
        return $this->render('data/newYearPlan.html.twig', $parameters);
    }

    /**
     * @Route("yearPlanList", name="yearPlanList")
     */
    public function yearPlan() {
        $user = $this->getUser();
        return $this->render('data/yearPlan.html.twig', ['yearPlan' => $user->getYearPlans()]);
    }

    /**
     * @Route("parcel", name="parcelList")
     */
    public function parcelList(Request $request) {
        $user = $this->getUser();
        $yearPlan = $user->getChoosedYearPlan();

        if ($yearPlan) { // If found yearPlan
            $fields = $yearPlan->getFields();
            $parameters = [
                'yearPlan' => $yearPlan,
                'start' => $yearPlan->getStartYear()
            ];
            return $this->render('data/parcel.html.twig', $parameters);
        }
        return $this->redirectToRoute('chooseYearPlan');
    }

    /**
     * @Route("fieldsTable", name="fieldsTable")
     */
    public function fieldsTable(Request $request) {
        $user = $this->getUser();
        $yearPlan = $user->getChoosedYearPlan();

        // if Not choosed
        if (!$yearPlan)
            return $this->redirectToRoute('chooseYearPlan');

        return $this->render('data/fieldsTable.twig', ['yearPlan' => $yearPlan]);
    }


    /**
     * @Route("fieldNewOrder", name="fieldNewOrder")
     */
    public function fieldNewOrder(Request $request) {
        $user = $this->getUser();
        $yearPlan = $user->getChoosedYearPlan();

        if ($yearPlan) { // If found yearPlan
            $entityManager = $this->getDoctrine()->getManager();
            foreach($yearPlan->getFields() as $field) {
                if($field->getNumber() >100) {
                    $number = (int) ($field->getNumber()/10);
                    $yearPlan->insertField($number,$field);
                    break;
                }
            
            }
            
            $entityManager->persist($yearPlan);
            $entityManager->flush();
        }

        return $this->redirectToRoute('field');
    }

        /**
     * @Route("fieldRenumerate", name="fieldRenumerate")
     */
    public function fieldRenumerate(Request $request) {
        $user = $this->getUser();
        $yearPlan = $user->getChoosedYearPlan();

        if ($yearPlan) { // If found yearPlan
            $entityManager = $this->getDoctrine()->getManager();
            $number = 1;
            foreach($yearPlan->getFields() as $field) {
                    $field->setNumber($number++);
                }
            }
            $entityManager->persist($yearPlan);
            $entityManager->flush();
            return $this->redirectToRoute('field');
        }


    /**
     * @Route("field", name="field")
     */
    public function field(Request $request) {
        $user = $this->getUser();
        $yearPlan = $user->getChoosedYearPlan();

        if ($yearPlan) { // If found yearPlan
            $fields = $yearPlan->getFields();
            $cultivatedArea = DataController::sumAreaEachField($fields);
            $parameters = [
                'start' => $yearPlan->getStartYear(),
                'field' => $fields,
                'cultivatedArea' => $cultivatedArea
            ];
            return $this->render('data/field.html.twig', $parameters);
        }

        return $this->redirectToRoute('chooseYearPlan');
    }

    /**
     * @Route("field/add", name="addField")
     */
    public function addField(Request $request) {
        $user = $this->getUser();
        $yearPlan = $user->getChoosedYearPlan();

        if ($yearPlan) {
            $operators = $yearPlan->getOperators();
            $entityManager = $this->getDoctrine()->getManager();

            $field = new Field();

            $field->setYearPlan($yearPlan);
            $field->setNewNumber();
            $form = $this->createForm(NewFieldFormType::class, $field, ['operators' => $operators]);
            $form->handleRequest($request);

            $errors = $form->getErrors(true);


            if ($form->isSubmitted() && $form->isValid()) {

                $this->addFlash('success', 'Pole ' . $field->getName() . ' zostało utworzone');
                $entityManager->persist($field);
                DataController::addYearToParcels($field, $entityManager);
                $entityManager->flush();

                unset($field);
                unset($form);
                $field = new Field();
                $form = $this->createForm(NewFieldFormType::class, $field, ['operators' => $operators]);
            }

            $parameters = [
                'yearPlan' => $yearPlan,
                'newFieldForm' => $form->createView(),
                'operators' => $operators,
                'errors' => $errors,
            ];
            return $this->render('data/newField.html.twig', $parameters);
        }
        return $this->redirectToRoute('chooseYearPlan');
    }

    /**
     * @Route("field/edit/{id}", name="editField")
     */
    public function editField($id, Request $request) {
        $user = $this->getUser();
        $yearPlan = $user->getChoosedYearPlan();

        if ($yearPlan) {
            $operators = $yearPlan->getOperators();
            $field = DataController::findFieldById($id, $user);
            if ($field) {
                $form = $this->createForm(NewFieldFormType::class, $field, array('operators' => $operators));
                $form->handleRequest($request);
                $errors = $form->getErrors(true);
                if ($form->isSubmitted() && $form->isValid()) {
                    $entityManager = $this->getDoctrine()->getManager();

                    if ($form->get('remove')->isClicked()) {
                        $entityManager->remove($field);
                        $entityManager->flush();
                        return $this->redirectToRoute('field');
                    }

                    DataController::addYearToParcels($field, $entityManager);

                    $entityManager->persist($field);
                    $entityManager->flush();
                    $this->addFlash('success', 'Pole ' . $field->getName() . ' zostało zmodyfikowane');
                }

                $parameters = [
                    'yearPlan' => $yearPlan,
                    'editFieldForm' => $form->createView(),
                    'operators' => $operators,
                    'errors' => $errors,
                ];

                return $this->render('data/editField.html.twig', $parameters);
            }
        }
        return $this->redirectToRoute('field');
    }

templates/data/chooseYearPlan.twig
{% extends 'base.html.twig' %}

{% block title %} Wybór planu {% endblock %}

{% block body %}
    <section id="content">
        <div class="container-fluid mt-3">
            <div class="row">

                <!--- Left menu -->
                <div class="col-md-2 mb-4">  
                    <ul class="nav nav-pills flex-column">
                        <li><a class="nav-link font-weight-bold" data-toggle="collapse" data-target=".d1" href="#" >Plany roczne</a></li>       
                        <li><ul style="padding-left: 20px; list-style: none">
                            <li><a class="d1 nav-link collapse" href="/yearPlanList" >Lista</a></li>
                            <li><a class="d1 nav-link collapse" href="/yearPlan/add" >Stwórz nowy plan</a></li>
                        </ul></li>
                        <li><a class="nav-link font-weight-bold" data-toggle="collapse" data-target=".d3" href="#" >Osoby</a></li>       
                        <li><ul style="padding-left: 20px; list-style: none">
                            <li><a class="d3 nav-link collapse" href="/operator" >Lista</a></li>
                            <li><a class="d3 nav-link collapse" href="/operator/add" >Dodaj</a></li>
                        </ul></li>
                        <li><a class="nav-link font-weight-bold" data-toggle="collapse" data-target=".d2" href="#" >Pola</a></li>
                        <li><ul style="padding-left: 20px; list-style: none">
                            <li><a class="d2 nav-link collapse" href="/field" >Lista</a></li>
                            <li><a class="d2 nav-link collapse" href="/field/add" >Stwórz nowe pole</a></li>
                        </ul></li>
                        <li><a class="nav-link font-weight-bold" href="/parcel" >Lista działek</a></li>
                        <li><a class="nav-link font-weight-bold" href="/fieldsTable" >Lista pól</a></li>
                        <li><a class="nav-link font-weight-bold" href="/selectPlants" >Wybierz rośliny</a></li>
                    </ul>
                </div> 

                <!--- Content -->
                <div class="col-md-10">
                    <div class="container-md mx-4">
                        <h2 class="text-center">Wybierz sezon</h2>     
                        <div class="table-responsive">
                            <table id="axs" class="text-center table w-75 mx-auto table-striped table-hover">
                                <thead>
                                    <tr>
                                        <th scope ="col">#</th>
                                        <th scope ="col">Rok rozpoczęcia</th>
                                        <th scope ="col">Rok zakończenia</th>
                                        <th scope ="col"></th> 
                                    </tr>
                                </thead>
                                <tbody >
                                    {% set licznik = 1 %}
                                    {% for item in yearPlanCollection %}
                                        <tr>
                                            <th class="align-middle" scope="row">{{ licznik }}</th>
                                            <td class="align-middle">{{ item.startYear }}</td>
                                            <td class="align-middle">{{ item.endYear }}</td>
                                            <td>
                                                <form method="POST" action="/setYearPlan">
                                                    <input type="hidden" name='yearPlan' value="{{ item.id }}"/>
                                                    <input type="submit" class="btn btn-secondary" value="Wybierz"/>
                                                </form>
                                            </td>
                                        </tr>
                                        {% set licznik = licznik+1 %}
                                    {% endfor %}

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!--- End content -->
        </div>                      
    </section>
{% endblock %}

templates/data/fieldsTable.twig
{% extends 'base.html.twig' %}

{% block title %} Lista działek {% endblock %}

{% block body %}
    <section id="content">
        <div class="container-fluid mt-3">
            <div class="row">
                <!--- Left menu -->
                <div class="col-md-2 mb-4">  
                    <ul class="nav nav-pills flex-column">
                        <li><a class="nav-link font-weight-bold" data-toggle="collapse" data-target=".d1" href="#" >Plany roczne</a></li>       
                        <li><ul style="padding-left: 20px; list-style: none">
                                <li><a class="d1 nav-link collapse" href="/yearPlanList" >Lista</a></li>
                                <li><a class="d1 nav-link collapse" href="/yearPlan/add" >Stwórz nowy plan</a></li>
                            </ul></li>
                        <li><a class="nav-link font-weight-bold" data-toggle="collapse" data-target=".d3" href="#" >Osoby</a></li>       
                        <li><ul style="padding-left: 20px; list-style: none">
                                <li><a class="d3 nav-link collapse" href="/operator" >Lista</a></li>
                                <li><a class="d3 nav-link collapse" href="/operator/add" >Dodaj</a></li>
                            </ul></li>
                        <li><a class="nav-link font-weight-bold" data-toggle="collapse" data-target=".d2" href="#" >Pola</a></li>
                        <li><ul style="padding-left: 20px; list-style: none">
                                <li><a class="d2 nav-link collapse" href="/field" >Lista</a></li>
                                <li><a class="d2 nav-link collapse" href="/field/add" >Stwórz nowe pole</a></li>
                            </ul></li>
                        <li><a class="nav-link font-weight-bold" href="/parcel" >Lista działek</a></li>
                        <li><a class="nav-link font-weight-bold active" href="/fieldsTable" >Lista pól</a></li>
                        <li><a class="nav-link font-weight-bold" href="/selectPlants" >Wybierz rośliny</a></li>
                    </ul>
                </div>

                <!--- Content -->
                <div class="col-md-10">
                    <div class="container-md mx-4">
                        <button class="float-right btn btn-primary" onClick="createPDF();">Drukuj</button>
                        <h2 class="text-center">Pola w sezonie {{ yearPlan.startYear }}/{{ yearPlan.endYear }} </h2>   

                        <div class="table-responsive">    

                            <table id="parcels" class="text-center table w-75 mx-auto">

                                <thead style="background-color: #32CD32">

                                    <tr>
                                        <th scope ="col">Numer pola</th>
                                        <th scope ="col">Pole</th>
                                        <th scope ="col">Numer działki</th>
                                        <th scope ="col">Powierzchnia[ha]</th>
                                        <th scope ="col">Dopłaty</th>
                                        <th scope ="col">Uprawa</th>
                                    </tr>
                                    <tr>
                                        <td class="align-middle"></td>
                                        <td class="align-middle"></td>
                                        <td class="align-middle"></td>
                                        <td class="align-middle"></td>
                                        <td class="align-middle">
                                            <select class="form-control" id="arimrOperatorSelect">
                                                <option selected="selected" value="all">Wszyscy</option>
                                                <option value="Brak">Brak</option>
                                                {% for operator in yearPlan.getOperators %}
                                                    <option value="{{ operator.getFirstName}}">{{ operator.getFirstName}}</option>
                                                {% endfor %}
                                            </select>
                                        </td>
                                        <td class="align-middle">
                                            <select class="form-control" id="plantNameSelect">
                                                <option selected="selected" value="all">Wszystkie</option>
                                                <option value="Nie ustalono">Nie ustalono</option>
                                                {% for plant in yearPlan.getPlants %} 
                                                    <option value="{{ plant.getName }}">{{ plant.getName }}</option>
                                                {% endfor %}
                                            </select>
                                        </td>
                                    </tr>
                                </thead>
                                <tbody id="rawTable" style="display: none;">


                                    {% set licznik = 1 %}
                                    {% for field in yearPlan.getFields %}
                                        <!-- Count amount of parcels -->
                                        {% set counter = 0 %}
                                        <!-- Display each parcel
                                        {% for item in field.getParcels %}
                                            <!-- Fuel status -->
                                            {% if item.fuelApplication == 1 %}
                                                {% set fuel = "Tak" %}
                                            {% else %}
                                                {% set fuel = "Nie" %}
                                            {% endif %}

                                            <!-- Arimr status -->
                                            {% if item.arimrOperator == NULL %}
                                                {% set operator = "Brak" %}
                                            {% else %}
                                                {% set operator = item.arimrOperator.firstname  %}
                                            {% endif %}


                                            <tr>
                                                <td name="fieldNumber" class="align-middle">{{ item.field.getNumber() }}</td>

                                                <td name="fieldName" class="no-hover align-middle" >{{ item.Field.getName() }}</td>


                                                <td hover class="align-middle">{{ item.parcelNumber }}</td>
                                                <td hover name ="area" class="align-middle">{{ item.getCultivatedAreaHa }}</td>
                                                <td hover name ="arimrOperator" class="align-middle">{{ operator }}</td>

                                                <td name ="plantName" class="no-hover align-middle" >{% if item.Field.plant %}{{ item.Field.plant.name }}{% else %}Nie ustalono{% endif %}</td>

                                            </tr>
                                            {% set licznik = licznik+1 %}
                                            {% set counter = counter+1 %}
                                        {% endfor %}
                                        {% set counter = 0 %}
                                    {% endfor %}



                                </tbody>
                            </table>
                        </div>  
                    </div>
                </div>
                <!--- End content -->

            </div>
        </div>                   
    </section>
    <script src="fieldsTableFilter.js"></script>
    <script src="generatePDF.js"></script>

    <script>
                                function createPDF() {
                                    var header = document.getElementsByTagName('h2')[0].textContent
                                    var arimr = document.getElementById('arimrOperatorSelect').value;
                                    if (arimr == 'all')
                                        arimr = 'Całość'
                                    var data = document.getElementById('filteredTable').cloneNode(true);
                                    var td = data.querySelectorAll("td[name=arimrOperator]");
                                    for(i=0;i<td.length;i++) {
                                        //console.log(  td[i]+"asd");
                                        td[i].remove();
                                    }
                                    console.log(data);
                                    
                                    
                                    var rowsLength = data.rows.length - 1;
                                    data.deleteRow(rowsLength);

                                    var before = '<h2>' + header + '- ' + arimr + '</h2>';
                                    data = data.innerHTML;
                                    var style = "<style>";
                                    style = style + "th {background-color: 	#32CD32}";
                                    style = style + "table {border-spacing: 0px;width: 100%;font: 17px Calibri;}";
                                    style = style + "table, th, td {border: solid 0.1px rgba(0, 0, 0, 0.5);";
                                    style = style + "padding: 2px 3px;text-align: center;}";
                                    style = style + "</style>";

                                    // CREATE A WINDOW OBJECT.
                                    var win = window.open('', '', 'height=700,width=700');

                                    win.document.write('<html><head>');
                                    //win.document.write('<title>Profile</title>');   // <title> FOR PDF HEADER.
                                    win.document.write(style);          // ADD STYLE INSIDE THE HEAD TAG.
                                    win.document.write('</head>');
                                    win.document.write('<body>');
                                    win.document.write('<table><tr><th scope = col colspan=7>' + before + '</th><tr><th scope ="col">Pole</th><th scope ="col">#</th><th scope ="col">Numer działki</th><th scope ="col">Powierzchnia[ha]</th><th scope ="col">Uprawa</th></tr>');
                                    //win.document.write('<table><tr><th scope = col colspan=7>' + before + '</th><tr><th scope ="col">Pole</th><th scope ="col">#</th><th scope ="col">Numer działki</th><th scope ="col">Powierzchnia[ha]</th><th scope ="col">Dopłaty</th><th scope ="col">Uprawa</th></tr>');
                                    win.document.write('<tbody>');
                                    win.document.write(data);         // THE TABLE CONTENTS INSIDE THE BODY TAG.
                                    win.document.write('</tbody>');
                                    win.document.write('</table');
                                    win.document.write('</body></html>');

                                    win.document.close(); 	// CLOSE THE CURRENT WINDOW.

                                    win.print();    // PRINT THE CONTENTS.
                                }
    </script>

{% endblock %}